### ISSUE TITLE
cstr_empty() can return false when size is 0

### ISSUE THREAD

**Issue by wmww** [stclib/STC#108]
To cut to the chase, looks like there's logic in `cstr_empty()` which assumes empty strings will always be represented by small strings, however this invariant is not held when resizing.

For example:
```c
#include <stdio.h>
#include "include/stc/cstr.h"

int main() {
    cstr s = cstr_lit("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    cstr_resize(&s, 0, '_');
    printf("Size: %zd\n", cstr_size(&s));
    printf("Empty: %s\n", cstr_empty(&s) ? "yes" : "no");
    return 0;
}
```
When compiled and run with `gcc cstr-empty-bug.c src/libstc.c -lm && ./a.out`, gives:
```
Size: 0
Empty: no
```

The code has to be slightly modified for the v50dev branch, but the results are the same there.

**Comment by tylov** [comment]
Thanks for reporting.
