### ISSUE TITLE
Support & Documentation for Critical Systems (determinism + avoid heap fragmentation)

### ISSUE THREAD

**Issue by therealdreg** [stclib/STC#66]
Hello @tylov! I find this library to be quite impressive. For individuals like myself who program critical embedded systems, we must utilize deterministic code (+avoid heap fragmentation), which means we cannot employ malloc/calloc. 

Typically, we resort to using "pools" and similar constructs, or allocate everything at the program's main. 

I believe it would be beneficial to incorporate support for such scenarios. 

I've reviewed your code, and several approaches come to mind. It would be valuable to document the most optimal method for this scenario (README)

**Comment by tylov** [comment]
Thanks. I'll try to mention this in the docs.

All STC containers except for linked lists can be preallocated with reserve(), and that includes sorted maps, queues and deques!  This is uncommon, as in c++ these containers normally allocates elements (as node or segments) incrementally, and does not provide reserve.
