### ISSUE TITLE
cvec doesn't compile with i_eq but no i_cmp.

### ISSUE THREAD

**Issue by notevenodd** [stclib/STC#68]
Can you compile this simple test? This fails for me and I'm not sure why.

```
typedef struct object {
  int a;
  int b;
} object;

bool object_eq(const object *obj1, const object *obj2)
{ return (obj1->a == obj2->a) && (obj1->b == obj2->b); }

#define i_type         test
#define i_val          object
#define i_eq           object_eq
#include "stc/cvec.h"  // <-- FAIL!!!
```

May affect other containers too, haven't tested.

**Comment by tylov** [comment]
Thanks, i have done some changes lately, but there was actually a small bug that caused this, and I accidently found it yesterday before seeing your message, so it is fixed now.

It also compiles without i_eq defined. i_eq enables find() / get() functions as you probably know.
