### ISSUE TITLE
Feature request: i_no_unicode flag

### ISSUE THREAD

**Issue by polijan** [stclib/STC#69]
Feature Request: could there be a i_no_unicode (or equivalent) at cstr inclusion so that it wouldn't define or try to compile utf-8 related functions? Of course, most projects should want utf-8 strings everywhere... but there are also simple tools where it's just not needed.

**Comment by tylov** [comment]
Hi. By default, there is only a few small utf8 inline function defined/included, i.e the ones in the utf8.h header, which allows you to iterate codepoints in utf8 strings. To get utf8 lowercase/uppercase or case-insensitive comparison functions you must either #define i_import before including one of the string/view headers, cregex or link with src/utf8code.c. cregex always requires linking with the utf8 character tables.

**Comment by polijan** [comment]
let's close the issue.
