### ISSUE TITLE
Questioning plans to disallow drop and clone on null Arc/Box 

### ISSUE THREAD

**Issue by wmww** [stclib/STC#86]
06a0342bba5da29739505016604b3ec672a809c5 in the [v50dev](https://github.com/stclib/STC/tree/v50dev) branch makes it undefined behavior to drop or clone a null arc or box. By my understanding this means to write a struct that is zero-initializable and contains arcs or boxes you will need to manually check if the arc/box is null in the drop and clone. It also means it's undefined to clone or drop another container (vec, hmap, etc) that contains a null arc or box. This seems like an unnecessary inconvenience and footgun to me, so I'd like to better understand the motivation.

Is it perf? If so, might there be some way to make the previous behavior optional?

Is it to discourage users from using these containers as nullable values? I get this sentiment, but since neither C nor STC has a great alternative to Rust Option or C++ std::optional, I think it's reasonable that we combine optionality with pointers in some cases.

**Comment by tylov** [comment]
Sorry for the late response. My intention was to discourage nullable smart pointers, but I agree that this will make them less useful and dangerous. Will revert this change.

**Comment by tylov** [comment]
You can look at the v50dev version with the fixes. (both arc and box).

**Comment by wmww** [comment]
I think assuming pointers by default for sorting is fine, especially since that's customizable. Thanks!
