### ISSUE TITLE
cbits include guard does not appear to be effective

### ISSUE THREAD

**Issue by thehoustonian** [stclib/STC#92]
I have noticed that the closing `#endif` for the include guard in `cbits.h`  (`#ifndef STC_CBITS_H_INCLUDED`) terminates on line 128 instead of closer to the end of the file. There are multiple functions that are defined below this `endif`, such as `cbits_init`, `cbits_size`, etc. This causes issues when importing `cbits.h` in multiple header files that are used elsewhere (such as in two libraries that another project pulls in, for example). I have resolved this by adding `ifndef` checks around the `#include "stc/cbits.h"` statements in each header, but this seems like a bug.

If I am using `cbits` incorrectly or this is otherwise not a bug, just let me know.

**Comment by tylov** [comment]
I think this is fixed in v50dev branch, but I will check again.

**Comment by tylov** [comment]
Confirmed fixed in v50dev branch.
