### ISSUE TITLE
Where is the `i_TYPE` macro defined?

### ISSUE THREAD

**Issue by jymchng** [stclib/STC#96]
Hi

Thank you for building this, it is a lovely library.

As I had just starting out to learning C (I know Rust, Go, Python and TypeScript), I am curious where is the `i_TYPE` macro defined, as it seems to generate `i_type` define macro and hence it is the type that has the data structures (maps, vector, etc) operate with.

Just wonder how this generic programming is being done.

**Comment by wondon101** [comment]
Hi, you could find their definations in <stc/types.h> and  <stc/priv/template.h>

**Comment by tylov** [comment]
`i_TYPE` will be replaced by `i_type` in V5.0, so it is deprecated until it is removed.
You can define the container name/type by defining **i_type NAME [, KEYTYPE [, VALTYPE]]**.
Or define `i_type NAME` and `i_key KEYTYPE` (and `i_val VALTYPE` for maps) separately.
